### ISSUE TITLE
frontend: rename menu titles in the sidenav

### ISSUE THREAD

**Issue by Lordnoname** [Werdenfels-Gymnasium/voting-calculator#39]

**Comment by gilgda** [comment]
Need further information what to rename into what, at the moment every view is named like it is named in the code: frontend/src/components/app.component.html - l.31

**Comment by Lordnoname** [comment]
I think the naming of the titles except for Login and Logout should be changed into a constant german name :) f.e.: Voting erstellen -> shorter name in german
Nope, you have to look into the app.component.ts file at line 18 at the name property.

**Comment by gilgda** [comment]
Ok thanks for the information 😉
