### ISSUE TITLE
Create print-template for assignments

### ISSUE THREAD

**Issue by Lordnoname** [Werdenfels-Gymnasium/voting-calculator#44]
Create this template in HTML, it should contain following variables:
- name of the current student
- assigned seminar
- if its their first, second or third vote
- percentage of getting first, second or third vote
- sign-field for the parents

**Comment by Lordnoname** [comment]
![image](https://user-images.githubusercontent.com/10695477/29903722-9138c904-8e05-11e7-9a43-f24292b8337e.png)

**Comment by gilgda** [comment]
Can we even show a result? I thought the original plan was to print out the vote and let the students´ parents sign it before handing it back to an administrator to confirm all votes and then print out the results.

**Comment by Lordnoname** [comment]
Yup. I managed to add a route that lets us prints the results individually for every student :)
Otherwise you need to print two pieces of paper for every student.

**Comment by gilgda** [comment]
Note: Agreed on two printouts with every evaluated voting, one for the student to let his/her parents confirm the vote and one for the results (displayed on one big list or one printout for every student)
