### ISSUE TITLE
frontend: fix bug in login view

### ISSUE THREAD

**Issue by gilgda** [Werdenfels-Gymnasium/voting-calculator#51]
placeholder input is not displayed correctly

**Comment by Lordnoname** [comment]
What is the issue exactly? I think the behaviour of the tooltip is normal.

**Comment by gilgda** [comment]
Yes the tooltip is behaving correctly but the label of the placeholder is displayed beneath the input line of the placeholder.

**Comment by gilgda** [comment]
Local problem
